### ISSUE TITLE
Error converting Level.sav

### ISSUE THREAD

**Issue by Henry-Hiles** [adefee/paver-palworld-save-editor#11]
```
Error converting Level.sav -> JSON: Error: Command failed: python "./helpers/cheahjs-save-tools/convert.py" "/home/quadradical/.steam/steam/steamapps/compatdata/1623730/pfx/drive_c/users/steamuser/AppData/Local/Pal/Saved/SaveGames/76561198261193584/88699368447B416DCB2266B79EFBA19F//Level.sav"
Traceback (most recent call last):
  File "/home/quadradical/Downloads/paver-palworld-save-editor/./helpers/cheahjs-save-tools/convert.py", line 160, in <module>
    main()
  File "/home/quadradical/Downloads/paver-palworld-save-editor/./helpers/cheahjs-save-tools/convert.py", line 71, in main
    convert_sav_to_json(
  File "/home/quadradical/Downloads/paver-palworld-save-editor/./helpers/cheahjs-save-tools/convert.py", line 114, in convert_sav_to_json
    gvas_file = GvasFile.read(
                ^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 279, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 292, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 403, in 
```struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 430, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 279, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 289, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/rawdata/map_object.py", line 21, in decode
    map_object["Model"]["value"]["RawData"]["value"] = map_model.decode_bytes(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/rawdata/map_model.py", line 42, in decode_bytes
    raise Exception("Warning: EOF not reached")
Exception: Warning: EOF not reached

Exporting report as JSON...
Report written written to "./paver-reports/pal-2024-08-30_174429-failed.json"
Paver has encountered critical errors and cannot continue. Please address the following issues and try again. The logs above likely contain more context. If you submit a bug report, please try to include the above logs, too.
[
  'Critical error encountered when converting Level.sav to JSON: Error: Command failed: python "./helpers/cheahjs-save-tools/convert.py" "/home/quadradical/.steam/steam/steamapps/compatdata/1623730/pfx/drive_c/users/steamuser/AppData/Local/Pal/Saved/SaveGames/76561198261193584/88699368447B416DCB2266B79EFBA19F//Level.sav"\n' +
    'Traceback (most recent call last):\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/./helpers/cheahjs-save-tools/convert.py", line 160, in <module>\n' +
    '    main()\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/./helpers/cheahjs-save-tools/convert.py", line 71, in main\n' +
    '    convert_sav_to_json(\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/./helpers/cheahjs-save-tools/convert.py", line 114, in convert_sav_to_json\n' +
    '    gvas_file = GvasFile.read(\n' +
    '                ^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/gvas.py", line 131, in read\n' +
    '    gvas_file.properties = reader.properties_until_end()\n' +
    '                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 279, in properties_until_end\n' +
    '    properties[name] = self.property(type_name, size, f"{path}.{name}")\n' +
    '                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 292, in property\n' +
    '    value = self.struct(path)\n' +
    '            ^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 403, in struct\n' +
    '    value = self.struct_value(struct_type, path)\n' +
    '            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 430, in struct_value\n' +
    '    return self.properties_until_end(path)\n' +
    '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 279, in properties_until_end\n' +
    '    properties[name] = self.property(type_name, size, f"{path}.{name}")\n' +
    '                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/archive.py", line 289, in property\n' +
    '    value = self.custom_properties[path][0](self, type_name, size, path)\n' +
    '            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/rawdata/map_object.py", line 21, in decode\n' +
    '    map_object["Model"]["value"]["RawData"]["value"] = map_model.decode_bytes(\n' +
    '                                                       ^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  File "/home/quadradical/Downloads/paver-palworld-save-editor/helpers/cheahjs-save-tools/palworld_save_tools/rawdata/map_model.py", line 42, in decode_bytes\n' +
    '    raise Exception("Warning: EOF not reached")\n' +
    'Exception: Warning: EOF not reached\n'
]
FYI: No additional warnings noted in this run.

**Comment by Henry-Hiles** [comment]
Huh maybe this isn't a paver issue: https://github.com/cheahjs/palworld-save-tools/issues/138
